project/Clase/urls.py
from django.urls import path
from . import views

app_name = 'Clase'

urlpatterns = [
    path('', views.home, name='home'),
    path('menu', views.menu, name='menu'),
    path('cursos', views.cursos, name="cursos"),
    path('profesores', views.profesores, name="profesores"),
    path('estudiantes', views.estudiantes, name="estudiantes"),
    path('comisiones', views.comisiones, name="comisiones"),
    path('buscar/', views.buscar),
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('Clase/', include('Clase.urls')),
]

project/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
]

project/Clase/models.py
from django.db import models

class Curso(models.Model):
    nombre = models.CharField(max_length=100)
    
    def __str__(self) -> str:
        return self.nombre

class Estudiante(models.Model):
    nombre = models.CharField(max_length=200)
    #curso = models.ForeignKey(Curso, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self) -> str:
        return self.nombre

class Profesor(models.Model):
    nombre = models.CharField(max_length=200)
    #curso = models.ForeignKey(Curso, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self) -> str:
        return self.nombre
    
class Comision(models.Model):  
    nombre = models.PositiveIntegerField(unique=True)
    curso = models.ForeignKey(Curso, on_delete=models.SET_NULL, null=True, blank=True)
    profesor = models.ForeignKey(Profesor, on_delete=models.SET_NULL, null=True, blank=True)
    estudiante = models.ManyToManyField(Estudiante)
    
    def __str__(self) -> str:
        return str(self.nombre)

project/core/models.py
from django.db import models

# Create your models here.

project/Clase/forms.py
from django import forms

class EstudianteFormulario(forms.Form):
    nombre = forms.CharField(max_length=100)

class ProfesorFormulario(forms.Form):   
    nombre= forms.CharField(max_length=100)
    
class CursoFormulario(forms.Form):
    nombre = forms.CharField(max_length=100)

project/Clase/views.py
from django.http.request import QueryDict
from django.shortcuts import render, HttpResponse
from django.http import HttpResponse
from .models import Curso, Profesor, Estudiante
from .forms import CursoFormulario, ProfesorFormulario, EstudianteFormulario

from . import models

# Create your views here.

def menu(request):
      return render(request, 'core/index.html')

def home(request):
    query = models.Comision.objects.all()
    context = {'comisiones': query}
    return render(request, 'Clase/index.html', context)

def curso(request):
      return render(request, "Clase/cursos.html")

def estudiante(request):
      return render(request, "Clase/estudiantes.html")

def comisiones(request):
      return render(request, "Clase/comisiones.html")

def cursos(request):
      if request.method == 'POST':
            miFormulario = CursoFormulario(request.POST)
            print(miFormulario)
            if miFormulario.is_valid:
                  informacion = miFormulario.cleaned_data
                  curso = Curso (nombre=informacion['nombre']) 
                  curso.save()
                  return render(request, "Clase/index.html")
      else: 
            miFormulario= CursoFormulario()
      return render(request, "Clase/cursos.html", {"miFormulario":miFormulario})


def profesores(request):
      if request.method == 'POST':
            miFormulario = ProfesorFormulario(request.POST)
            print(miFormulario)
            if miFormulario.is_valid:
                  informacion = miFormulario.cleaned_data
                  profesor = Profesor (nombre=informacion['nombre']) 
                  profesor.save()
                  return render(request, "Clase/index.html")
      else: 
            miFormulario= ProfesorFormulario()
      return render(request, "Clase/profesores.html", {"miFormulario":miFormulario})
  
def estudiantes(request):
      if request.method == 'POST':
            miFormulario = EstudianteFormulario(request.POST)
            print(miFormulario)
            if miFormulario.is_valid:
                  informacion = miFormulario.cleaned_data
                  estudiante = Estudiante (nombre=informacion['nombre']) 
                  estudiante.save()
                  return render(request, "Clase/index.html")
      else: 
            miFormulario= ProfesorFormulario()
      return render(request, "Clase/profesores.html", {"miFormulario":miFormulario})
  
def buscar(request):
      if  request.GET["comisiones"]:
            comisiones = request.GET['comisiones'] 
            cursos = Curso.objects.filter(comisiones__icontains=comisiones)
            return render(request, "Clase/index.html", {"comisiones":comisiones})
      else: 
	      respuesta = "No pediste datos"
      return HttpResponse(respuesta)

project/core/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'core/index.html')

project/Clase/templates/Clase/comisiones.html
{% extends "core/base.html" %}

{% load static %}

{% block content %}

    <h1>Comisiones</h1>
    <p>Aquí está la información de las Comisiones</p>  

    {% for comision in comisiones %}

        <p>{{ comision.nombre }} | {{ comision.curso }} | {{ comision.profesor }}</p>

    {% endfor %}

    <h1>Cursos</h1>
    <p>Aquí está la información de los Cursos</p>  

    {% for curso in cursos %}

        <p>{{ curso.nombre }}</p>

    {% endfor %}

    <h1>Profesores</h1>
    <p>Aquí está la información de los Profesores</p>  

    {% for profesor in profesores %}

        <p>{{ profesor.nombre }}</p>

    {% endfor %}

    <h1>Estudiantes</h1>
    <p>Aquí está la información de los Estudiantes</p>  

    {% for estudiante in estudiantes %}

    <p>{{ estudiantes.nombre }}</p>

    {% endfor %}

{% endblock %}

project/Clase/templates/Clase/cursos.html
{% extends "core/base.html" %}

{% block content %}

    <h1>Formulario - Agregar Curso</h1>
    
    {% if miFormulario.errors %}

    <p style="color: red;">Datos erróneos, revisar</p>

    {% endif %}

    <form action="" method="POST">{% csrf_token %}

        <table>

            {{ miFormulario.as_table }}

        </table>

        <input type="submit", value="Enviar">

    </form>

{% endblock %}

project/Clase/templates/Clase/estudiantes.html
{% extends "core/base.html" %}

{% block content %}

    <h1>Formulario - Agregar Estudiante</h1>
    
    {% if miFormulario.errors %}

    <p style="color: red;">Datos erróneos, revisar</p>

    {% endif %}

    <form action="" method="POST">{% csrf_token %}

        <table>

            {{ miFormulario.as_table }}

        </table>

        <input type="submit", value="Enviar">

    </form>

{% endblock %}

project/Clase/templates/Clase/index.html
{% extends 'core/base.html' %}

{% block title %}
    <nav class="navbar navbar-light bg-light static-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'Clase:menu' %}">Inicio</a>
            <a class="navbar-brand" href="{% url 'Clase:profesores' %}">Profesores</a>
            <a class="navbar-brand" href="{% url 'Clase:cursos' %}">Cursos</a>
            <a class="navbar-brand" href="{% url 'Clase:estudiantes' %}">Estudiantes</a>
            <a class="navbar-brand" href="{% url 'Clase:comisiones' %}">Comisiones</a>
        </div>
    </nav>
{% endblock title %}

{% block content %}

    <h3>Buscar comisión:</h3>

    <form action="/Clase/buscar/" method="GET">

        <input type="text" name="comisiones" id="comisiones">
        <input type="submit" value="Buscar">

    </form>

    {% if comisiones %}

        <p>Estamos la comisión: {{ comision }}</p>

    {% for comision in comisiones %}

        <p>{{ comision.nombre }} | {{ comision.curso }} | {{ comision.profesor }}</p>

    {% endfor %}

    {% endif %}
{% endblock content %}

project/Clase/templates/Clase/profesores.html
{% extends "core/base.html" %}

{% block content %}

    <h1>Formulario - Agregar Profesor</h1>
    
    {% if miFormulario.errors %}

    <p style="color: red;">Datos erróneos, revisar</p>

    {% endif %}

    <form action="" method="POST">{% csrf_token %}

        <table>

            {{ miFormulario.as_table }}

        </table>

        <input type="submit", value="Enviar">

    </form>

{% endblock %}

project/core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi Proyecto</title>
</head>
<body>
    {% block title %}
    {% endblock title %}
    
    {% block content %}
    {% endblock content %}
</body>
</html>

project/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
    <h1>Página inicial</h1>
{% endblock title %}

{% block content %}
    <ul>
        <li>
            <a href="{% url "Clase:home" %}">Clase</a>
        </li>
    </ul>
{% endblock content %}